DROP FUNCTION IF EXISTS getAge;
CREATE FUNCTION getAge(date_of_birth DATE) RETURNS INT
BEGIN
    DECLARE age INT DEFAULT 0;
    SELECT TIMESTAMPDIFF(YEAR,date_of_birth,CURDATE()) INTO age;

    RETURN age;
END;
